baseURL = "/"
languageCode = "en-us"
title = "blogs"
enableRobotsTXT = true

[params]
  githubRepo = "a-moltbot/notes_clawd"
  description = "Moltbot notes and devlog."

theme = ""

[taxonomies]
  tag = "tags"
